// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRMf6hcUHjopuujbT7QO4vsgGkZwrWooA',
    appId: '1:969502932777:web:a5bacbed8fcbd480474138',
    messagingSenderId: '969502932777',
    projectId: 'mypetfit-c530e',
    authDomain: 'mypetfit-c530e.firebaseapp.com',
    storageBucket: 'mypetfit-c530e.firebasestorage.app',
    measurementId: 'G-QZH82DVX7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtSCsT4K5q4Cj_Neu_WlSqIHxdn6S5Us',
    appId: '1:969502932777:android:4a06a52965b75db5474138',
    messagingSenderId: '969502932777',
    projectId: 'mypetfit-c530e',
    storageBucket: 'mypetfit-c530e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbiGcPQY_NfWjvhdTJrYMwjdK47_stQZc',
    appId: '1:969502932777:ios:5f9345233d5cccb9474138',
    messagingSenderId: '969502932777',
    projectId: 'mypetfit-c530e',
    storageBucket: 'mypetfit-c530e.firebasestorage.app',
    iosBundleId: 'com.mypetfit.mypetfitApp',
  );
}
